version: '3.9'

services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    restart: unless-stopped
    environment:
      - DB_SERVER_HOST=zabbix-postgres
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=secret
    networks:
      - zabbix
    ports:
      - "10051:10051"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10051/"]
      interval: 30s
      timeout: 10s
      retries: 3

  zabbix-web-nginx:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    restart: unless-stopped
    environment:
      - DB_SERVER_HOST=zabbix-postgres
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=secret
      - ZBX_SERVER_HOST=zabbix-server
    networks:
      - zabbix
    ports:
      - "8081:8080"

  zabbix-postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=secret
    networks:
      - zabbix

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    restart: unless-stopped
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_HOSTNAME=Zabbix server
    networks:
      - zabbix

networks:
  zabbix: