[project]
name = "tablichkin-backend"
version = "0.0.1"
description = "tablichkin is a realtime cooperative web spreadsheet editor"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.119.0",
    "psycopg2>=2.9.11",
]
